# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

get_mcmc_hbsarv10 <- function(data_all, xdelta, xgrid, xrange, xinx, xover, nobs1, iptHB1, xmin, ztz, vtv, wtw, phi2, cpara, probit_para, gamma_para, tau_para, eta_para, met_para, theta0_para, squish_para1, squish_para2, sigma_para, v_para, z_para, phi_para, fx_para, basis_para, alpha, betall, phi, lambda, lambdai, thetall, theta0, xiparall, xipar0, gammall, tau2all, tauall, sigma2, sigma, bFlagHBsigma, bFlagpsi, bFlagCenter, bFlaglm, iflagpn, iflagsc, bFlagZ, disp) {
    .Call(`_HBSARSC_get_mcmc_hbsarv10`, data_all, xdelta, xgrid, xrange, xinx, xover, nobs1, iptHB1, xmin, ztz, vtv, wtw, phi2, cpara, probit_para, gamma_para, tau_para, eta_para, met_para, theta0_para, squish_para1, squish_para2, sigma_para, v_para, z_para, phi_para, fx_para, basis_para, alpha, betall, phi, lambda, lambdai, thetall, theta0, xiparall, xipar0, gammall, tau2all, tauall, sigma2, sigma, bFlagHBsigma, bFlagpsi, bFlagCenter, bFlaglm, iflagpn, iflagsc, bFlagZ, disp)
}

rcpp_CumTrap <- function(f, delta) {
    .Call(`_HBSARSC_rcpp_CumTrap`, f, delta)
}

rcpp_trapint <- function(f, xdelta) {
    .Call(`_HBSARSC_rcpp_trapint`, f, xdelta)
}

rcpp_GetSquish <- function(omega, psi, xgrid) {
    .Call(`_HBSARSC_rcpp_GetSquish`, omega, psi, xgrid)
}

get_ex_idx <- function(len, idx) {
    .Call(`_HBSARSC_get_ex_idx`, len, idx)
}

rcpp_rndtna <- function(mu, sigma, xtop) {
    .Call(`_HBSARSC_rcpp_rndtna`, mu, sigma, xtop)
}

rcpp_rndtnb <- function(mu, sigma, xbot) {
    .Call(`_HBSARSC_rcpp_rndtnb`, mu, sigma, xbot)
}

rcpp_rndtnb2 <- function(mu, sigma, xbot) {
    .Call(`_HBSARSC_rcpp_rndtnb2`, mu, sigma, xbot)
}

rcpp_rndtnab <- function(mu, sigma, xbot, xtop) {
    .Call(`_HBSARSC_rcpp_rndtnab`, mu, sigma, xbot, xtop)
}

rcpp_Getf0x <- function(f0pars) {
    .Call(`_HBSARSC_rcpp_Getf0x`, f0pars)
}

rcpp_Getfx <- function(fpars) {
    .Call(`_HBSARSC_rcpp_Getfx`, fpars)
}

rcpp_GetMonofxgrid <- function(fpars) {
    .Call(`_HBSARSC_rcpp_GetMonofxgrid`, fpars)
}

rcpp_GetMonoSamefxgrid <- function(fpars) {
    .Call(`_HBSARSC_rcpp_GetMonoSamefxgrid`, fpars)
}

rcpp_GetMonoDiffxgrid <- function(fpars) {
    .Call(`_HBSARSC_rcpp_GetMonoDiffxgrid`, fpars)
}

rcpp_GetUfxgrid <- function(fpars) {
    .Call(`_HBSARSC_rcpp_GetUfxgrid`, fpars)
}

rcpp_GetSfxgrid <- function(fpars, d3) {
    .Call(`_HBSARSC_rcpp_GetSfxgrid`, fpars, d3)
}

rcpp_GetMonof0xgrid <- function(f0pars) {
    .Call(`_HBSARSC_rcpp_GetMonof0xgrid`, f0pars)
}

rcpp_GetMonoSamef0xgrid <- function(f0pars) {
    .Call(`_HBSARSC_rcpp_GetMonoSamef0xgrid`, f0pars)
}

rcpp_GetMonoDiff0xgrid <- function(f0pars) {
    .Call(`_HBSARSC_rcpp_GetMonoDiff0xgrid`, f0pars)
}

rcpp_GetUf0xgrid <- function(f0pars) {
    .Call(`_HBSARSC_rcpp_GetUf0xgrid`, f0pars)
}

rcpp_GetSf0xgrid <- function(f0pars, d3) {
    .Call(`_HBSARSC_rcpp_GetSf0xgrid`, f0pars, d3)
}

rcpp_GetUpfxgrid <- function(fpara, phix, xdelta, xrange, centering) {
    .Call(`_HBSARSC_rcpp_GetUpfxgrid`, fpara, phix, xdelta, xrange, centering)
}

rcpp_GetSCfxobs <- function(xgrid, xinx, xover, fxgrid, iflagpn) {
    .Call(`_HBSARSC_rcpp_GetSCfxobs`, xgrid, xinx, xover, fxgrid, iflagpn)
}

rcpp_GetUpf0xgrid <- function(fpara, vpara, phix, phix2, xdelta, xrange, centering) {
    .Call(`_HBSARSC_rcpp_GetUpf0xgrid`, fpara, vpara, phix, phix2, xdelta, xrange, centering)
}

rcpp_GetUpf0Biasxgrid <- function(fpara, phix, xdelta, xrange, centering) {
    .Call(`_HBSARSC_rcpp_GetUpf0Biasxgrid`, fpara, phix, xdelta, xrange, centering)
}

rcpp_GetMonof <- function(theta, phixobs, uquadfacts, quadfacts, fpm) {
    .Call(`_HBSARSC_rcpp_GetMonof`, theta, phixobs, uquadfacts, quadfacts, fpm)
}

rcpp_QuadMult <- function(x, qvech, uquadfacts, quadfacts) {
    .Call(`_HBSARSC_rcpp_QuadMult`, x, qvech, uquadfacts, quadfacts)
}

rcpp_cholSol <- function(b, U) {
    .Call(`_HBSARSC_rcpp_cholSol`, b, U)
}

IntCos2 <- function(x, kall, xmin, xrange, nbasis) {
    .Call(`_HBSARSC_IntCos2`, x, kall, xmin, xrange, nbasis)
}

IntCosCrossProd <- function(x, j, k, xmin, xrange) {
    .Call(`_HBSARSC_IntCosCrossProd`, x, j, k, xmin, xrange)
}

IntConst2 <- function(x, xmin, xrange) {
    .Call(`_HBSARSC_IntConst2`, x, xmin, xrange)
}

IntCos <- function(x, kall, xmin, xrange, nbasis) {
    .Call(`_HBSARSC_IntCos`, x, kall, xmin, xrange, nbasis)
}

vech <- function(A) {
    .Call(`_HBSARSC_vech`, A)
}

computeBasis <- function(xobs, xmin, xrange, nobs, nbasis, nr) {
    .Call(`_HBSARSC_computeBasis`, xobs, xmin, xrange, nobs, nbasis, nr)
}

update_lambda <- function(lambda, lambdai, resid_mat, lambda_g0i, lambda_fn, nparw) {
    invisible(.Call(`_HBSARSC_update_lambda`, lambda, lambdai, resid_mat, lambda_g0i, lambda_fn, nparw))
}

update_phi <- function(lambdai, ztz, phi_v0i, zdata, betall, nparw, nparz, phidim) {
    .Call(`_HBSARSC_update_phi`, lambdai, ztz, phi_v0i, zdata, betall, nparw, nparz, phidim)
}

GetMetVec <- function(w, m0, alpha, ndim) {
    .Call(`_HBSARSC_GetMetVec`, w, m0, alpha, ndim)
}

SetMetVec <- function(Met, w, m0, alpha, ndim) {
    invisible(.Call(`_HBSARSC_SetMetVec`, Met, w, m0, alpha, ndim))
}

AdaptMetVar <- function(x) {
    .Call(`_HBSARSC_AdaptMetVar`, x)
}

AdaptMetUpdate <- function(x) {
    invisible(.Call(`_HBSARSC_AdaptMetUpdate`, x))
}

AdaptMetUpdate2 <- function(x) {
    .Call(`_HBSARSC_AdaptMetUpdate2`, x)
}

UpdateMet <- function(x, nb, fct) {
    invisible(.Call(`_HBSARSC_UpdateMet`, x, nb, fct))
}

UpdateMet2 <- function(x, nb, fct) {
    .Call(`_HBSARSC_UpdateMet2`, x, nb, fct)
}

